title: config blender
description: a lightweight daemon that watches, merges, and rebuilds app configs (KDL, YAML, TOML, JSON, INI, RAW)
logo: assets/logo.png
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
