name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"

      # PREVENT go.sum churn during tests
      - name: Download modules
        run: go mod download all

      - name: Verify workspace clean (pre-test)
        run: git diff --exit-code

      - name: Run tests (readonly modules)
        env:
          GOFLAGS: -mod=readonly
        run: go test ./...

      - name: Verify workspace clean (pre-release)
        run: git diff --exit-code

      - name: GoReleaser - release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
